name: Build and Release Windows Executable

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: python build.py

    - name: Rename executable with tag
      run: |
        $tag = "${{ github.ref_name }}"
        $originalFile = "dist\ImageManager.exe"
        $newFile = "dist\ImageManager-$tag.exe"
        if (Test-Path $originalFile) {
          Rename-Item $originalFile $newFile
          Write-Host "Renamed $originalFile to $newFile"
        } else {
          Write-Host "Original file not found: $originalFile"
          exit 1
        }

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: image-dataset-manager-windows-${{ github.ref_name }}
        path: dist/*.exe
        retention-days: 30

    - name: Get latest commit message
      id: commit
      run: |
        echo "commit_msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.exe
        tag_name: ${{ github.ref_name }}
        release_name: Image Dataset Manager ${{ github.ref_name }}
        body: ${{ steps.commit.outputs.commit_msg }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
